apiVersion: mongodbcommunity.mongodb.com/v1
kind: MongoDBCommunity
metadata:
  name: mongodb-test
spec:
  members: 1
  type: ReplicaSet
  version: "7.0.12"
  security:
    authentication:
      modes: ["SCRAM"]
  users:
    - name: admin
      db: admin
      passwordSecretRef:
        name: mongodb-admin-password
      roles:
        - name: clusterAdmin
          db: admin
        - name: userAdminAnyDatabase
          db: admin
      scramCredentialsSecretName: mongodb-admin-scram
  additionalMongodConfig:
    storage.wiredTiger.engineConfig.journalCompressor: snappy
  statefulSet:
    spec:
      template:
        spec:
          containers:
            - name: mongod
              image: 273828039634.dkr.ecr.ap-southeast-1.amazonaws.com/mongodb-community-server:7.0.12
            - name: mongodb-agent
              image: 273828039634.dkr.ecr.ap-southeast-1.amazonaws.com/mongodb-agent:108.0.6.8796-1
      volumeClaimTemplates:
        - metadata:
            name: data-volume
          spec:
            storageClassName: gp2
            accessModes: ["ReadWriteOnce"]
            resources:
              requests:
                storage: 5Gi
        - metadata:
            name: logs-volume
          spec:
            storageClassName: gp2
            accessModes: ["ReadWriteOnce"]
            resources:
              requests:
                storage: 2Gi
---
apiVersion: v1
kind: Secret
metadata:
  name: mongodb-admin-password
type: Opaque
stringData:
  password: "TestPass123!"
